name: Build and Deploy Kingshot Wiki

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install markdown jinja2 argostranslate beautifulsoup4 requests

    - name: Install Argos Translate model
      run: |
        curl -L -o model.argosmodel https://argos-net.com/v1/translate-en_ja-1_1.argosmodel
        python -c "import argostranslate.package; argostranslate.package.install_from_path('model.argosmodel')"

    - name: Run mirror + generate
      run: |
        python mirror.py
        python generate_site.py

    - name: Check output contents
      run: |
        echo "Output directory contents:"
        ls -R output
        
    - name: Check output contents abs
      run: |
        echo "Output directory contents:"
        ls -R /home/runner/work/kingshot/kingshot/output/*

    - name: Check output contents abs_all
      run: |
        echo "Output directory contents:"
        ls -all /home/runner/work/kingshot/kingshot/
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: output
