
name: Build and Deploy Kingshot Wiki

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install markdown jinja2 argostranslate

    - name: Install Argos Translate model
      run: |
        curl -L -o model.argosmodel https://www.argosopentech.com/argospm/packages/translate-en_ja-1_0.argosmodel
        python -c "import argostranslate.package; argostranslate.package.install_from_path('model.argosmodel')"

    - name: Run mirror + generate
      run: |
        python mirror.py
        python generate_site.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output
